version: '3.8'

services:
  lint:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/app
    command: >
      sh -c "flake8 . && black --check . && isort --check-only ."