# strategies/mean_reversion.py
import numpy as np
import pandas as pd
from typing import Dict, List, Optional, Tuple, Union
from dataclasses import dataclass
import logging
from datetime import datetime, timedelta
import json
from pathlib import Path

# Technical analysis indicators
from ta.momentum import RSIIndicator
from ta.volatility import BollingerBands, AverageTrueRange
from ta.trend import ADXIndicator

logger = logging.getLogger('MeanReversion')

@dataclass
class TradeSignal:
    """Container for trade signals generated by the strategy."""
    symbol: str
    direction: str  # 'long' or 'short'
    entry_price: float
    stop_loss: float
    take_profit: float
    confidence: float
    timestamp: datetime
    metadata: Optional[Dict] = None

class MeanReversionStrategy:
    """
    Advanced Mean Reversion Strategy using Bollinger Bands, RSI, and ATR.
    
    This strategy identifies overbought/oversold conditions using RSI and Bollinger Bands,
    with additional confirmation from volume and volatility indicators. It includes
    position sizing based on ATR and dynamic stop-loss/take-profit levels.
    """
    
    def __init__(
        self,
        symbol: str = "BTC/USDT",
        bb_period: int = 20,
        bb_std: float = 2.0,
        rsi_period: int = 14,
        rsi_oversold: float = 30.0,
        rsi_overbought: float = 70.0,
        atr_period: int = 14,
        atr_multiplier: float = 2.0,
        adx_period: int = 14,
        min_adx: float = 25.0,
        min_consolidation_bars: int = 5,
        max_trade_duration: int = 24,  # hours
        risk_reward_ratio: float = 1.5,
        use_trailing_stop: bool = True,
        trailing_stop_multiplier: float = 1.5,
        max_position_size: float = 0.1,  # Max position size as fraction of account
        config_path: Optional[str] = None
    ):
        """
        Initialize the Mean Reversion Strategy.
        
        Args:
            symbol: Trading pair symbol (e.g., 'BTC/USDT')
            bb_period: Bollinger Bands period
            bb_std: Number of standard deviations for Bollinger Bands
            rsi_period: RSI period
            rsi_oversold: RSI oversold threshold
            rsi_overbought: RSI overbought threshold
            atr_period: ATR period for volatility measurement
            atr_multiplier: ATR multiplier for stop loss
            adx_period: ADX period for trend strength
            min_adx: Minimum ADX value to consider a trend
            min_consolidation_bars: Minimum bars of consolidation required
            max_trade_duration: Maximum trade duration in hours
            risk_reward_ratio: Risk:Reward ratio for take profit
            use_trailing_stop: Whether to use trailing stop
            trailing_stop_multiplier: Multiplier for trailing stop distance
            max_position_size: Maximum position size as fraction of account
            config_path: Path to configuration file (optional)
        """
        self.symbol = symbol
        self.bb_period = bb_period
        self.bb_std = bb_std
        self.rsi_period = rsi_period
        self.rsi_oversold = rsi_oversold
        self.rsi_overbought = rsi_overbought
        self.atr_period = atr_period
        self.atr_multiplier = atr_multiplier
        self.adx_period = adx_period
        self.min_adx = min_adx
        self.min_consolidation_bars = min_consolidation_bars
        self.max_trade_duration = max_trade_duration
        self.risk_reward_ratio = risk_reward_ratio
        self.use_trailing_stop = use_trailing_stop
        self.trailing_stop_multiplier = trailing_stop_multiplier
        self.max_position_size = max_position_size
        
        # Load configuration if provided
        if config_path:
            self.load_config(config_path)
            
        self.logger = logging.getLogger(f'MeanReversion_{self.symbol.replace("/", "_")}')
        self._validate_parameters()
        
    def _validate_parameters(self):
        """Validate strategy parameters."""
        if self.bb_period < 1:
            raise ValueError("Bollinger Bands period must be >= 1")
        if self.rsi_period < 1:
            raise ValueError("RSI period must be >= 1")
        if self.atr_period < 1:
            raise ValueError("ATR period must be >= 1")
        if self.adx_period < 1:
            raise ValueError("ADX period must be >= 1")
        if not (0 < self.rsi_oversold < self.rsi_overbought < 100):
            raise ValueError("Invalid RSI thresholds")
        if self.atr_multiplier <= 0:
            raise ValueError("ATR multiplier must be positive")
        if self.risk_reward_ratio <= 0:
            raise ValueError("Risk:Reward ratio must be positive")
            
    def load_config(self, config_path: str) -> None:
        """
        Load strategy configuration from a JSON file.
        
        Args:
            config_path: Path to the configuration file
        """
        try:
            with open(config_path, 'r') as f:
                config = json.load(f)
                
            # Update strategy parameters from config
            if 'strategy' in config and 'mean_reversion' in config['strategy']:
                params = config['strategy']['mean_reversion']
                for key, value in params.items():
                    if hasattr(self, key):
                        setattr(self, key, value)
                        self.logger.info(f"Updated parameter {key} = {value}")
                        
        except Exception as e:
            self.logger.error(f"Error loading config: {e}")
            raise
            
    def calculate_indicators(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Calculate all technical indicators required by the strategy.
        
        Args:
            df: DataFrame with OHLCV data (must contain 'open', 'high', 'low', 'close', 'volume')
            
        Returns:
            DataFrame with added indicator columns
        """
        if df.empty:
            return df
            
        df = df.copy()
        
        # Bollinger Bands
        bb = BollingerBands(
            close=df['close'],
            window=self.bb_period,
            window_dev=self.bb_std
        )
        df['bb_upper'] = bb.bollinger_hband()
        df['bb_middle'] = bb.bollinger_mavg()
        df['bb_lower'] = bb.bollinger_lband()
        df['bb_width'] = (df['bb_upper'] - df['bb_lower']) / df['bb_middle']
        df['bb_%b'] = (df['close'] - df['bb_lower']) / (df['bb_upper'] - df['bb_lower'])
        
        # RSI
        rsi = RSIIndicator(
            close=df['close'],
            window=self.rsi_period
        )
        df['rsi'] = rsi.rsi()
        
        # ATR for volatility
        atr = AverageTrueRange(
            high=df['high'],
            low=df['low'],
            close=df['close'],
            window=self.atr_period
        )
        df['atr'] = atr.average_true_range()
        
        # ADX for trend strength
        adx_ind = ADXIndicator(
            high=df['high'],
            low=df['low'],
            close=df['close'],
            window=self.adx_period
        )
        df['adx'] = adx_ind.adx()
        df['adx_pos'] = adx_ind.adx_pos()
        df['adx_neg'] = adx_ind.adx_neg()
        
        # Volume indicators
        df['volume_ma'] = df['volume'].rolling(window=20).mean()
        df['volume_ratio'] = df['volume'] / df['volume_ma']
        
        # Price change and volatility
        df['returns'] = df['close'].pct_change()
        df['volatility'] = df['returns'].rolling(window=20).std() * np.sqrt(252)  # Annualized
        
        # Identify consolidation periods
        df['consolidation'] = self._identify_consolidation(df)
        
        return df
        
    def _identify_consolidation(
        self,
        df: pd.DataFrame,
        lookback: int = None,
        threshold: float = 0.01
    ) -> pd.Series:
        """
        Identify consolidation periods based on price range.
        
        Args:
            df: DataFrame with price data
            lookback: Number of bars to look back (default: min_consolidation_bars)
            threshold: Price range threshold for consolidation
            
        Returns:
            Boolean Series indicating consolidation periods
        """
        if lookback is None:
            lookback = self.min_consolidation_bars
            
        rolling_high = df['high'].rolling(window=lookback).max()
        rolling_low = df['low'].rolling(window=lookback).min()
        range_pct = (rolling_high - rolling_low) / rolling_low
        
        return range_pct < threshold
        
    def generate_signals(self, df: pd.DataFrame) -> List[TradeSignal]:
        """
        Generate trading signals based on mean reversion strategy.
        
        Args:
            df: DataFrame with OHLCV data and indicators
            
        Returns:
            List of TradeSignal objects
        """
        if df.empty or len(df) < max(self.bb_period, self.rsi_period, self.atr_period, self.adx_period) + 1:
            return []
            
        # Calculate indicators if not already present
        required_columns = ['bb_upper', 'bb_middle', 'bb_lower', 'rsi', 'atr', 'adx', 'consolidation']
        if not all(col in df.columns for col in required_columns):
            df = self.calculate_indicators(df)
            
        signals = []
        latest = df.iloc[-1]
        prev = df.iloc[-2] if len(df) > 1 else latest
        
        # Check for valid data
        if (pd.isna(latest['bb_lower']) or pd.isna(latest['rsi']) or 
            pd.isna(latest['atr']) or pd.isna(latest['adx'])):
            return []
            
        # Long signal (oversold)
        long_condition = (
            latest['close'] <= latest['bb_lower'] and  # Price below lower BB
            latest['rsi'] < self.rsi_oversold and      # RSI below oversold
            latest['consolidation'] and                # In consolidation
            latest['adx'] < self.min_adx and           # No strong trend
            latest['volume_ratio'] > 0.8               # Some volume
        )
        
        # Short signal (overbought)
        short_condition = (
            latest['close'] >= latest['bb_upper'] and  # Price above upper BB
            latest['rsi'] > self.rsi_overbought and    # RSI above overbought
            latest['consolidation'] and                # In consolidation
            latest['adx'] < self.min_adx and           # No strong trend
            latest['volume_ratio'] > 0.8               # Some volume
        )
        
        # Generate signals
        if long_condition:
            signal = self._create_signal(df, 'long')
            if signal:
                signals.append(signal)
                
        elif short_condition:
            signal = self._create_signal(df, 'short')
            if signal:
                signals.append(signal)
                
        return signals
        
    def _create_signal(
        self,
        df: pd.DataFrame,
        direction: str
    ) -> Optional[TradeSignal]:
        """
        Create a trade signal with proper risk management.
        
        Args:
            df: DataFrame with price and indicator data
            direction: 'long' or 'short'
            
        Returns:
            TradeSignal if valid, None otherwise
        """
        latest = df.iloc[-1]
        
        # Calculate entry, stop loss, and take profit
        if direction == 'long':
            entry_price = latest['close']
            atr = latest['atr']
            stop_loss = entry_price - (atr * self.atr_multiplier)
            take_profit = entry_price + (atr * self.atr_multiplier * self.risk_reward_ratio)
            
            # Adjust for support/resistance levels if available
            if 'support' in df.columns and not pd.isna(latest['support']):
                stop_loss = min(stop_loss, latest['support'] * 0.995)  # 0.5% below support
                
        else:  # short
            entry_price = latest['close']
            atr = latest['atr']
            stop_loss = entry_price + (atr * self.atr_multiplier)
            take_profit = entry_price - (atr * self.atr_multiplier * self.risk_reward_ratio)
            
            # Adjust for resistance levels if available
            if 'resistance' in df.columns and not pd.isna(latest['resistance']):
                stop_loss = max(stop_loss, latest['resistance'] * 1.005)  # 0.5% above resistance
                
        # Calculate confidence (0-1)
        confidence = self._calculate_confidence(df, direction)
        
        # Create metadata
        metadata = {
            'atr': float(latest['atr']),
            'rsi': float(latest['rsi']),
            'bb_width': float(latest['bb_width']),
            'adx': float(latest['adx']),
            'volume_ratio': float(latest['volume_ratio']),
            'consolidation': bool(latest['consolidation'])
        }
        
        return TradeSignal(
            symbol=self.symbol,
            direction=direction,
            entry_price=float(entry_price),
            stop_loss=float(stop_loss),
            take_profit=float(take_profit),
            confidence=float(confidence),
            timestamp=datetime.utcnow(),
            metadata=metadata
        )
        
    def _calculate_confidence(self, df: pd.DataFrame, direction: str) -> float:
        """
        Calculate confidence score (0-1) for a potential trade.
        
        Args:
            df: DataFrame with price and indicator data
            direction: 'long' or 'short'
            
        Returns:
            Confidence score between 0 and 1
        """
        latest = df.iloc[-1]
        confidence = 0.5  # Base confidence
        
        # RSI position (0-1)
        if direction == 'long':
            rsi_norm = (self.rsi_oversold - latest['rsi']) / self.rsi_oversold
        else:  # short
            rsi_norm = (latest['rsi'] - self.rsi_overbought) / (100 - self.rsi_overbought)
            
        # BB position (0-1)
        if direction == 'long':
            bb_norm = (latest['bb_lower'] - latest['close']) / (latest['bb_upper'] - latest['bb_lower'])
        else:  # short
            bb_norm = (latest['close'] - latest['bb_upper']) / (latest['bb_upper'] - latest['bb_lower'])
            
        # Volume confirmation (0.5-1.5)
        volume_factor = min(1.5, max(0.5, latest['volume_ratio']))
        
        # Combine factors with weights
        confidence = (
            0.4 * rsi_norm + 
            0.4 * bb_norm + 
            0.1 * volume_factor +
            0.1 * (1.0 - min(1.0, latest['adx'] / 50.0))  # Lower ADX is better for mean reversion
        )
        
        # Ensure within bounds
        return max(0.0, min(1.0, confidence))
        
    def manage_trade(
        self,
        position: Dict,
        current_price: float,
        current_time: datetime,
        df: Optional[pd.DataFrame] = None
    ) -> Dict:
        """
        Manage an open trade (check stop loss, take profit, trailing stop, etc.)
        
        Args:
            position: Dictionary containing position details
            current_price: Current market price
            current_time: Current time
            df: Optional DataFrame with recent price data for advanced management
            
        Returns:
            Updated position dictionary with any actions taken
        """
        position = position.copy()
        
        # Check if trade has expired
        trade_duration = (current_time - position['entry_time']).total_seconds() / 3600  # hours
        if trade_duration > self.max_trade_duration:
            position['action'] = 'close'
            position['reason'] = 'timeout'
            position['exit_price'] = current_price
            return position
            
        # Update current price and P&L
        position['current_price'] = current_price
        if position['direction'] == 'long':
            position['unrealized_pnl'] = (current_price - position['entry_price']) * position['size']
            position['unrealized_pnl_pct'] = (current_price / position['entry_price'] - 1) * 100
        else:  # short
            position['unrealized_pnl'] = (position['entry_price'] - current_price) * position['size']
            position['unrealized_pnl_pct'] = (1 - current_price / position['entry_price']) * 100
            
        # Check stop loss and take profit
        if position['direction'] == 'long':
            # Check stop loss
            if current_price <= position['stop_loss']:
                position['action'] = 'close'
                position['reason'] = 'stop_loss'
                position['exit_price'] = position['stop_loss']
                return position
                
            # Check take profit
            if current_price >= position['take_profit']:
                position['action'] = 'close'
                position['reason'] = 'take_profit'
                position['exit_price'] = position['take_profit']
                return position
                
            # Trailing stop
            if self.use_trailing_stop and 'highest_price' in position:
                trail_stop = position['highest_price'] - (position['atr'] * self.atr_multiplier * self.trailing_stop_multiplier)
                position['stop_loss'] = max(position['stop_loss'], trail_stop)
                
            # Update highest price
            if 'highest_price' not in position or current_price > position['highest_price']:
                position['highest_price'] = current_price
                
        else:  # short
            # Check stop loss
            if current_price >= position['stop_loss']:
                position['action'] = 'close'
                position['reason'] = 'stop_loss'
                position['exit_price'] = position['stop_loss']
                return position
                
            # Check take profit
            if current_price <= position['take_profit']:
                position['action'] = 'close'
                position['reason'] = 'take_profit'
                position['exit_price'] = position['take_profit']
                return position
                
            # Trailing stop
            if self.use_trailing_stop and 'lowest_price' in position:
                trail_stop = position['lowest_price'] + (position['atr'] * self.atr_multiplier * self.trailing_stop_multiplier)
                position['stop_loss'] = min(position['stop_loss'], trail_stop)
                
            # Update lowest price
            if 'lowest_price' not in position or current_price < position['lowest_price']:
                position['lowest_price'] = current_price
                
        # Additional checks if DataFrame is provided
        if df is not None and len(df) > 0:
            latest = df.iloc[-1]
            
            # Check for trend reversal (exit if strong trend develops)
            if 'adx' in latest and not pd.isna(latest['adx']):
                if latest['adx'] > self.min_adx * 1.5:  # Strong trend developing
                    position['action'] = 'close'
                    position['reason'] = 'trend_developing'
                    position['exit_price'] = current_price
                    return position
                    
            # Check for volatility contraction (exit if volatility drops too much)
            if 'atr' in latest and 'atr' in position and not pd.isna(latest['atr']):
                atr_ratio = latest['atr'] / position['atr']
                if atr_ratio < 0.5:  # Volatility dropped significantly
                    position['action'] = 'close'
                    position['reason'] = 'low_volatility'
                    position['exit_price'] = current_price
                    return position
                    
        position['action'] = 'hold'
        return position
        
    def calculate_position_size(
        self,
        entry_price: float,
        stop_loss: float,
        account_balance: float,
        risk_per_trade: float = 0.01,
        max_position_size: float = None
    ) -> Tuple[float, float]:
        """
        Calculate position size based on account balance and risk parameters.
        
        Args:
            entry_price: Entry price
            stop_loss: Stop loss price
            account_balance: Current account balance
            risk_per_trade: Fraction of account to risk per trade
            max_position_size: Maximum position size as fraction of account
            
        Returns:
            Tuple of (position_size, position_value)
        """
        if max_position_size is None:
            max_position_size = self.max_position_size
            
        # Calculate risk amount
        risk_amount = account_balance * risk_per_trade
        
        # Calculate position size
        if entry_price <= 0 or stop_loss <= 0:
            return 0.0, 0.0
            
        risk_per_share = abs(entry_price - stop_loss)
        if risk_per_share == 0:
            return 0.0, 0.0
            
        position_size = risk_amount / risk_per_share
        
        # Apply position size limits
        max_size = (account_balance * max_position_size) / entry_price
        position_size = min(position_size, max_size)
        
        # Calculate position value
        position_value = position_size * entry_price
        
        return position_size, position_value
        
    def backtest(
        self,
        df: pd.DataFrame,
        initial_balance: float = 10000.0,
        risk_per_trade: float = 0.01,
        commission: float = 0.001,
        slippage: float = 0.0005
    ) -> Dict:
        """
        Backtest the mean reversion strategy on historical data.
        
        Args:
            df: DataFrame with OHLCV data
            initial_balance: Starting account balance
            risk_per_trade: Fraction of account to risk per trade
            commission: Commission per trade (fraction)
            slippage: Slippage per trade (fraction)
            
        Returns:
            Dictionary with backtest results
        """
        if df.empty:
            return {}
            
        # Calculate indicators
        df = self.calculate_indicators(df)
        
        # Initialize variables
        balance = initial_balance
        equity = [initial_balance]
        trades = []
        position = None
        trade_id = 0
        
        # Main backtest loop
        for i in range(1, len(df)):
            current = df.iloc[i]
            prev = df.iloc[i-1]
            
            # Generate signals on previous bar
            signals = self.generate_signals(df.iloc[:i])
            
            # Check for entry signals if not in a trade
            if position is None and signals:
                signal = signals[0]  # Take the first signal if multiple
                
                # Calculate position size
                position_size, _ = self.calculate_position_size(
                    entry_price=signal.entry_price,
                    stop_loss=signal.stop_loss,
                    account_balance=balance,
                    risk_per_trade=risk_per_trade
                )
                
                if position_size > 0:
                    # Calculate commission and slippage
                    trade_value = position_size * signal.entry_price
                    commission_cost = trade_value * commission
                    slippage_cost = trade_value * slippage
                    
                    # Open position
                    position = {
                        'id': trade_id,
                        'entry_time': current.name if hasattr(current, 'name') else i,
                        'entry_price': signal.entry_price,
                        'stop_loss': signal.stop_loss,
                        'take_profit': signal.take_profit,
                        'size': position_size,
                        'direction': signal.direction,
                        'atr': current['atr'],
                        'commission': commission_cost,
                        'slippage': slippage_cost
                    }
                    
                    # Update balance
                    balance -= commission_cost + slippage_cost
                    trade_id += 1
                    
            # Manage open position
            elif position is not None:
                # Check exit conditions
                current_price = current['close']
                current_time = current.name if hasattr(current, 'name') else i
                
                # Update position with current price
                position['current_price'] = current_price
                
                # Manage the trade
                position = self.manage_trade(
                    position,
                    current_price=current_price,
                    current_time=current_time,
                    df=df.iloc[:i+1]  # All data up to current bar
                )
                
                # Check if we need to close the position
                if position['action'] == 'close':
                    # Calculate P&L
                    if position['direction'] == 'long':
                        pnl = (position['exit_price'] - position['entry_price']) * position['size']
                    else:  # short
                        pnl = (position['entry_price'] - position['exit_price']) * position['size']
                        
                    # Apply commission and slippage
                    trade_value = position['size'] * position['exit_price']
                    commission_cost = trade_value * commission
                    slippage_cost = trade_value * slippage
                    pnl -= (commission_cost + slippage_cost)
                    
                    # Update balance
                    balance += pnl
                    
                    # Record trade
                    trade = {
                        'id': position['id'],
                        'entry_time': position['entry_time'],
                        'exit_time': current_time,
                        'entry_price': position['entry_price'],
                        'exit_price': position['exit_price'],
                        'size': position['size'],
                        'direction': position['direction'],
                        'pnl': pnl,
                        'pnl_pct': (pnl / (position['size'] * position['entry_price'])) * 100,
                        'reason': position['reason'],
                        'commission': position['commission'] + commission_cost,
                        'slippage': position['slippage'] + slippage_cost
                    }
                    trades.append(trade)
                    
                    # Reset position
                    position = None
                    
            # Update equity curve
            if position is not None:
                # Calculate unrealized P&L
                if position['direction'] == 'long':
                    unrealized_pnl = (current['close'] - position['entry_price']) * position['size']
                else:  # short
                    unrealized_pnl = (position['entry_price'] - current['close']) * position['size']
                equity.append(balance + unrealized_pnl)
            else:
                equity.append(balance)
                
        # Calculate performance metrics
        df_equity = pd.Series(equity, index=df.index[:len(equity)])
        returns = df_equity.pct_change().dropna()
        
        # Calculate metrics
        total_return = (df_equity.iloc[-1] / df_equity.iloc[0] - 1) * 100
        sharpe_ratio = self._calculate_sharpe_ratio(returns)
        max_drawdown = self._calculate_max_drawdown(df_equity)
        win_rate = self._calculate_win_rate(trades) if trades else 0
        
        # Prepare results
        results = {
            'initial_balance': initial_balance,
            'final_balance': df_equity.iloc[-1],
            'total_return_pct': total_return,
            'total_trades': len(trades),
            'win_rate': win_rate,
            'sharpe_ratio': sharpe_ratio,
            'max_drawdown': max_drawdown,
            'equity_curve': df_equity,
            'trades': trades
        }
        
        return results
        
    def _calculate_sharpe_ratio(self, returns: pd.Series, risk_free_rate: float = 0.0) -> float:
        """Calculate annualized Sharpe ratio."""
        if len(returns) < 2:
            return 0.0
        excess_returns = returns - risk_free_rate / 252  # Assuming daily returns
        return (excess_returns.mean() / (excess_returns.std() + 1e-9)) * np.sqrt(252)
        
    def _calculate_max_drawdown(self, equity: pd.Series) -> float:
        """Calculate maximum drawdown."""
        if len(equity) == 0:
            return 0.0
        rolling_max = equity.cummax()
        drawdowns = (equity - rolling_max) / rolling_max
        return abs(drawdowns.min()) * 100  # as percentage
        
    def _calculate_win_rate(self, trades: List[Dict]) -> float:
        """Calculate win rate from trade history."""
        if not trades:
            return 0.0
        winning_trades = sum(1 for t in trades if t['pnl'] > 0)
        return (winning_trades / len(trades)) * 100
        
    def optimize_parameters(
        self,
        df: pd.DataFrame,
        param_grid: Optional[Dict] = None,
        initial_balance: float = 10000.0,
        risk_per_trade: float = 0.01,
        commission: float = 0.001,
        n_trials: int = 100
    ) -> Dict:
        """
        Optimize strategy parameters using random search.
        
        Args:
            df: DataFrame with OHLCV data
            param_grid: Dictionary of parameter ranges to search
            initial_balance: Starting account balance
            risk_per_trade: Fraction of account to risk per trade
            commission: Commission per trade
            n_trials: Number of random parameter combinations to try
            
        Returns:
            Dictionary with best parameters and results
        """
        import random
        
        # Default parameter grid
        if param_grid is None:
            param_grid = {
                'bb_period': range(10, 51, 5),
                'bb_std': [1.5, 2.0, 2.5, 3.0],
                'rsi_period': range(7, 22, 2),
                'rsi_oversold': range(20, 41
                                'rsi_overbought': range(60, 81),
                'atr_period': range(10, 31, 5),
                'atr_multiplier': [1.5, 2.0, 2.5, 3.0],
                'min_adx': range(15, 31, 5)
            }
        
        best_params = None
        best_sharpe = -float('inf')
        results = []
        
        for _ in range(n_trials):
            # Sample random parameters
            params = {k: random.choice(v) for k, v in param_grid.items()}
            
            # Update strategy with new parameters
            for key, value in params.items():
                setattr(self, key, value)
            
            # Run backtest
            try:
                result = self.backtest(
                    df=df.copy(),
                    initial_balance=initial_balance,
                    risk_per_trade=risk_per_trade,
                    commission=commission
                )
                
                if result and 'sharpe_ratio' in result:
                    results.append((params, result))
                    
                    # Update best parameters
                    if result['sharpe_ratio'] > best_sharpe:
                        best_sharpe = result['sharpe_ratio']
                        best_params = params
                        
            except Exception as e:
                self.logger.warning(f"Backtest failed with params {params}: {e}")
        
        # Sort results by Sharpe ratio
        results.sort(key=lambda x: x[1].get('sharpe_ratio', -float('inf')), reverse=True)
        
        return {
            'best_params': best_params,
            'best_sharpe': best_sharpe,
            'all_results': [{'params': p, 'metrics': m} for p, m in results]
        }

    def save_strategy(self, filepath: str) -> bool:
        """Save strategy parameters to a JSON file."""
        params = {
            'symbol': self.symbol,
            'bb_period': self.bb_period,
            'bb_std': self.bb_std,
            'rsi_period': self.rsi_period,
            'rsi_oversold': self.rsi_oversold,
            'rsi_overbought': self.rsi_overbought,
            'atr_period': self.atr_period,
            'atr_multiplier': self.atr_multiplier,
            'adx_period': self.adx_period,
            'min_adx': self.min_adx,
            'min_consolidation_bars': self.min_consolidation_bars,
            'max_trade_duration': self.max_trade_duration,
            'risk_reward_ratio': self.risk_reward_ratio,
            'use_trailing_stop': self.use_trailing_stop,
            'trailing_stop_multiplier': self.trailing_stop_multiplier,
            'max_position_size': self.max_position_size
        }
        
        try:
            with open(filepath, 'w') as f:
                json.dump(params, f, indent=2)
            return True
        except Exception as e:
            self.logger.error(f"Error saving strategy: {e}")
            return False

    @classmethod
    def load_strategy(cls, filepath: str) -> 'MeanReversionStrategy':
        """Load strategy parameters from a JSON file."""
        try:
            with open(filepath, 'r') as f:
                params = json.load(f)
            return cls(**params)
        except Exception as e:
            logger.error(f"Error loading strategy: {e}")
            raise