apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../prod-stable
  - ../../cert-manager/clusterissuer-letsencrypt-prod.yaml
patchesStrategicMerge:
  - certificate-issuer.patch.yaml
commonLabels:
  env: prod
